### ISSUE TITLE
Cannot enlarge memory arrays

### ISSUE THREAD

**Issue by DrSnuggles** [wothke/playmod#2]
Happens in Chrome after playing back some YM files using ayumi backend.

`
Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at la (<anonymous>:27:24)
    at x (<anonymous>:104:347)
    at qa (<anonymous>:29:15)
    at enlargeMemory (<anonymous>:41:53)
    at tc (<anonymous>:49:68823)
    at cb (<anonymous>:49:18739)
    at bb (<anonymous>:49:12767)
    at va (<anonymous>:49:996)
    at Z._loadSongFile (<anonymous>:69:225)
    at Object.a.ccall (<anonymous>:79:279)
`

PS: Thanks for your great work !!

**Comment by wothke** [comment]
added missing cleanup of previous song's frame_data. plz let me know if this solved the problem.

**Comment by DrSnuggles** [comment]
sorry to say but problem still exists.
had similar problem while playing around with wasm version of libopenxmp. using js version caused no problem.

**Comment by wothke** [comment]
but it isn't just one particular song that needs more memory? and you did use the updated version and not something old that your browser might have cached? how many songs does it take to reproduce the problem?

**Comment by DrSnuggles** [comment]
i refreshed like a god :) using dev console + cache killer for chrome.
just checked again in new window. took about 60 songs in YM/Allister Brimble dir.
it is song independent and as soon as error occurs i can not play back any YM song.

tested in Firefox and faced same error message, but this browser still can play back some songs after error occured.

**Comment by wothke** [comment]
oops.. you tested on my  "playmod" page or locally? (I had just checked in my fix but NOT uploaded it to my page - I did upload it now)

**Comment by DrSnuggles** [comment]
i was using your www.wothke.ch/playmod page.
problem solved. thank you very much
do i miss one of your repositories?

**Comment by wothke** [comment]
https://github.com/wothke/webAyumi
